[package]
authors     = { workspace = true }
categories  = ["development-tools::testing", "simulation"]
description = "Simulator Utils package"
edition     = { workspace = true }
keywords    = ["deterministic", "simulator", "test", "utils"]
license     = { workspace = true }
name        = "simvar_utils"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
examples = false

[package.metadata.workspaces]
group = "simvar"

[dependencies]
switchy = { workspace = true, features = [
    "async",
    "async-macros",
    "async-util",
] }

[dev-dependencies]
serial_test = { workspace = true }
switchy_async = { workspace = true, features = ["macros", "sync", "time", "tokio"] }
test-log = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
default = []

fail-on-warnings = ["switchy/fail-on-warnings"]
