name: Create MoosicBox Tauri App Release

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  path: MoosicBoxServer

            - name: Get latest stable release of MoosicBox Tauri App
              uses: rez0n/actions-github-release@main
              id: stable_release
              env:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  repository: '${{ github.repository }}'
                  type: 'stable'

            - uses: ncipollo/release-action@v1
              with:
                  token: ${{ secrets.WORKFLOW_MANAGEMENT_TOKEN }}
                  tag: '${{ github.ref_name }}'
                  prerelease: false
                  body: |
                      **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.stable_release.outputs.release || github.head_ref || github.ref_name }}...${{ github.ref_name }}
                  generateReleaseNotes: false
