[package]
authors     = { workspace = true }
categories  = ["gui", "web-programming"]
description = "MoosicBox Marketing Website UI"
edition     = { workspace = true }
keywords    = ["dom", "gui", "transformer", "web"]
license     = { workspace = true }
name        = "moosicbox_marketing_site_ui"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = false

[dependencies]
hyperchad = { workspace = true, features = [
    "actions",
    "actions-logic",
    "actions-serde",
    "color",
    "renderer",
    "router",
    "template",
    "transformer",
] }

bytesize = { workspace = true }
chrono   = { workspace = true }
log      = { workspace = true }
regex    = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }

[features]
default = []

fail-on-warnings = ["hyperchad/fail-on-warnings"]

bundled_images = []
