[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools::procedural-macro-helpers"]
description = "MoosicBox env utilities package"
edition     = "2021"
keywords    = ["env", "environment", "util", "utilities", "utils"]
license     = "MPL-2.0"
name        = "moosicbox_env_utils"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
thiserror = { workspace = true }

[features]
fail-on-warnings = []
