allowed-duplicate-crates = [
    "audiopus_sys",
    "aws-smithy-json",
    "base64",
    "bitflags",
    "block2",
    "brotli-decompressor",
    "convert_case",
    "cookie",
    "core-foundation",
    "crc",
    "crc-catalog",
    "dirs",
    "dirs-sys",
    "env_logger",
    "fallible-iterator",
    "foreign-types",
    "foreign-types-shared",
    "getrandom",
    "glow",
    "h2",
    "hashbrown",
    "hashlink",
    "heck",
    "hermit-abi",
    "hostname",
    "http",
    "http-body",
    "hyper",
    "hyper-rustls",
    "indexmap",
    "itertools",
    "itoa",
    "libloading",
    "lru",
    "memoffset",
    "miniz_oxide",
    "mio",
    "ndk",
    "ndk-sys",
    "nix",
    "num-derive",
    "objc2",
    "objc2-app-kit",
    "objc2-foundation",
    "objc2-quartz-core",
    "ordered-float",
    "parking_lot",
    "parking_lot_core",
    "phf",
    "phf_macros",
    "phf_shared",
    "polling",
    "proc-macro-crate",
    "rand",
    "rand_chacha",
    "rand_core",
    "redox_syscall",
    "redox_users",
    "regex-automata",
    "regex-syntax",
    "reqwest",
    "roxmltree",
    "rustc-hash",
    "rustls",
    "rustls-pemfile",
    "rustls-webpki",
    "serde_yaml",
    "siphasher",
    "spin",
    "strsim",
    "strum",
    "strum_macros",
    "syn",
    "sync_wrapper",
    "thiserror",
    "thiserror-impl",
    "tokio-rustls",
    "toml_edit",
    "tower",
    "trackable",
    "ttf-parser",
    "wasi",
    "webpki-roots",
    "winapi",
    "windows",
    "windows-core",
    "windows-result",
    "windows-strings",
    "windows-sys",
    "windows-target",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_aarch_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "winnow",
    "winreg",
    "zerocopy",
    "zerocopy-derive",
]
