[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "Basic web server simulation example using simvar and moosicbox_web_server"
edition     = { workspace = true }
keywords    = ["simulation", "simvar", "web-server"]
license     = { workspace = true }
name        = "simvar_basic_web_server_example"
publish     = false
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
tests = false

[dependencies]
moosicbox_web_server = { workspace = true, features = [
    "actix",
    "cors",
    "serde",
] }
simvar = { workspace = true, features = ["http", "tcp", "time", "web-server"] }
switchy_async = { workspace = true, features = ["simulator", "tokio"] }
switchy_http = { workspace = true, features = ["simulator"] }
switchy_http_models = { workspace = true }
switchy_time = { workspace = true, features = ["simulator"] }

log        = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[features]
default = []

fail-on-warnings = [
    "moosicbox_web_server/fail-on-warnings",
    "simvar/fail-on-warnings",
    "switchy_async/fail-on-warnings",
    "switchy_http/fail-on-warnings",
    "switchy_http_models/fail-on-warnings",
    "switchy_time/fail-on-warnings",
]
