[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "MoosicBox resampler package"
edition     = { workspace = true }
keywords    = ["audio", "pcm", "resample", "resampler", "samples"]
license     = { workspace = true }
name        = "moosicbox_resampler"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = true

[dependencies]
arrayvec  = { workspace = true }
log       = { workspace = true }
profiling = { workspace = true, optional = true }
rubato    = { workspace = true }
symphonia = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }

[features]
default = []

fail-on-warnings = []

profiling = ["dep:profiling"]
