[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools"]
description = "MoosicBox resampler package"
edition     = "2021"
keywords    = ["audio", "pcm", "resample", "resampler", "samples"]
license     = "MPL-2.0"
name        = "moosicbox_resampler"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
arrayvec  = { workspace = true }
log       = { workspace = true }
profiling = { workspace = true, optional = true }
rubato    = { workspace = true }
symphonia = { workspace = true }

[features]
default = []

fail-on-warnings = []

profiling = ["dep:profiling"]
