[package]
authors     = { workspace = true }
description = "MoosicBox Web Server Nested GET example"
edition     = { workspace = true }
license     = { workspace = true }
name        = "web_server_nested_get"
publish     = false
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
tests = false

[dependencies]
moosicbox_web_server = { workspace = true, features = ["actix", "cors"] }

env_logger = { workspace = true }
tokio      = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
moosicbox_web_server = { workspace = true, features = ["simulator"] }

switchy_async       = { workspace = true, features = ["macros"] }
switchy_http_models = { workspace = true }
test-log            = { workspace = true }

[features]
default = []

fail-on-warnings = ["moosicbox_web_server/fail-on-warnings"]
