[package]
authors     = { workspace = true }
categories  = ["gui", "web-programming"]
description = "HyperChad HTML CDN optimization utilities"
edition     = { workspace = true }
keywords    = ["cdn", "gui", "html", "optimization", "web"]
license     = { workspace = true }
name        = "hyperchad_renderer_html_cdn"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = false

[package.metadata.workspaces]
group = "hyperchad"

[dependencies]
hyperchad_renderer = { workspace = true }
hyperchad_router   = { workspace = true, features = ["static-routes"] }

log = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
switchy_async     = { workspace = true, features = ["macros", "tokio"] }
test-log          = { workspace = true }
tokio             = { workspace = true }

[features]
default = []

fail-on-warnings = [
    "hyperchad_renderer/fail-on-warnings",
    "hyperchad_router/fail-on-warnings",
]
