[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "HyperChad template actions DSL macros package"
edition     = { workspace = true }
keywords    = ["async", "dsl"]
license     = { workspace = true }
name        = "hyperchad_template_actions_dsl"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = false

[package.metadata.workspaces]
group = "hyperchad"

[lib]
proc-macro = true

[dependencies]
hyperchad_actions = { workspace = true }

log         = { workspace = true }
proc-macro2 = { workspace = true }
quote       = { workspace = true }
syn         = { workspace = true, features = ["extra-traits", "full"] }

[dev-dependencies]
test-log = { workspace = true }

[features]
default = []

fail-on-warnings = ["hyperchad_actions/fail-on-warnings"]
