[package]
authors     = { workspace = true }
categories  = ["asynchronous", "development-tools"]
description = "Switchy Async macros package"
edition     = { workspace = true }
keywords    = ["async"]
license     = { workspace = true }
name        = "switchy_async_macros"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = false

[package.metadata.workspaces]
group = "switchy"

[lib]
proc-macro = true

[dependencies]
log = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = [
    "extra-traits",
    "full",
    "parsing",
    "visit-mut",
] }

[features]
default = ["simulator"]

fail-on-warnings = []

simulator = []
