[package]
authors     = { workspace = true }
categories  = ["codec", "encoding", "multimedia"]
description = "MoosicBox Opus codec decoder implementation for Symphonia"
edition     = { workspace = true }
keywords    = ["audio", "codec", "decoder", "opus", "symphonia"]
license     = { workspace = true }
name        = "moosicbox_opus"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.1"

[package.metadata]
examples = false

[dependencies]
audiopus  = { workspace = true }
bytes     = { workspace = true }
log       = { workspace = true }
symphonia = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
test-case         = { workspace = true }
test-log          = { workspace = true }

[features]
default          = []
fail-on-warnings = []
