[package]
authors     = { workspace = true }
categories  = ["development-tools", "network-programming"]
description = "Basic handler example demonstrating HttpRequest API across backends"
edition     = { workspace = true }
keywords    = ["async", "example", "http", "network", "web"]
license     = { workspace = true }
name        = "basic_handler_example"
publish     = false
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
tests = false

[dependencies]
moosicbox_web_server = { workspace = true, default-features = false }

[features]
default = ["simulator"]

fail-on-warnings = ["moosicbox_web_server/fail-on-warnings"]

actix     = ["moosicbox_web_server/actix"]
simulator = ["moosicbox_web_server/simulator"]
