[package]
authors     = { workspace = true }
description = "Simulated cancel async runtime usage example"
edition     = { workspace = true }
license     = { workspace = true }
name        = "async_cancel"
publish     = false
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
tests = false

[dependencies]
switchy_async = { workspace = true, features = ["simulator", "time", "util"] }

ctrlc             = { workspace = true }
pretty_env_logger = { workspace = true }

[features]
default = []

fail-on-warnings = ["switchy_async/fail-on-warnings"]
