[package]
authors     = { workspace = true }
description = "Switchy Web Server Simple GET example"
edition     = { workspace = true }
license     = { workspace = true }
name        = "switchy_web_server_example_simple_get"
publish     = false
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
tests = false

[package.metadata.workspaces]
group = "switchy"

[dependencies]
switchy_web_server = { workspace = true, features = ["actix", "cors"] }

env_logger = { workspace = true }
switchy = { workspace = true, features = [
    "async-net",
    "async-rt-multi-thread",
    "async-time",
    "async-tokio",
] }

[features]
default = []

fail-on-warnings = [
    "switchy/fail-on-warnings",
    "switchy_web_server/fail-on-warnings",
]
