[package]
authors     = { workspace = true }
categories  = ["development-tools", "network-programming"]
description = "Switchy Web Server basic handler example demonstrating RequestData extraction without serde dependencies"
edition     = { workspace = true }
keywords    = ["async", "example", "http", "network", "web"]
license     = { workspace = true }
name        = "switchy_web_server_example_basic_handler_standalone"
publish     = false
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
tests = false

[package.metadata.workspaces]
group = "switchy"

[features]
actix            = ["switchy_web_server/actix"]
default          = ["simulator"]
fail-on-warnings = ["switchy_web_server/fail-on-warnings"]
simulator        = ["switchy_web_server/simulator"]

[dependencies]
switchy_web_server = { workspace = true, features = ["simulator"] }
