[[ci-steps]]
toolchain = "free_disk_space"

[[feature-validation.override]]
dependencies = ["switchy_database", "switchy_uuid"]
feature      = "uuid"
reason       = "switchy's uuid feature is not intended to propagate to these dependencies"
type         = "allow-missing"

[[config]]
os = "ubuntu"

[[config.dependencies]]
command = "sudo apt-get update && sudo apt-get install libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpango1.0-dev libgl1-mesa-dev libglu1-mesa-dev"
