[package]
authors     = ["Braden Steffaniak"]
categories  = ["gui"]
description = "MoosicBoxApp client package"
edition     = "2021"
keywords    = ["client"]
license     = "MPL-2.0"
name        = "moosicbox_app_client"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../../../assert", default-features = false }

log = { workspace = true }

[features]
default = []

fail-on-warnings = []
