[package]
authors     = { workspace = true }
categories  = ["asynchronous", "development-tools"]
description = "Cargo async linter package"
edition     = { workspace = true }
keywords    = ["async"]
license     = { workspace = true }
name        = "switchy_async_cargo"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = false

[dependencies]
clap              = { workspace = true }
log               = { workspace = true }
pretty_env_logger = { workspace = true }
syn               = { workspace = true, features = ["full", "visit"] }
walkdir           = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }

[features]
default = []

fail-on-warnings = []
