[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "Test utilities for clippier package testing"
edition     = { workspace = true }
keywords    = ["clippier", "testing", "util"]
license     = { workspace = true }
name        = "clippier_test_utilities"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = false
tests    = false

[dependencies]
clippier = { workspace = true, features = ["test-utils"] }
serde = { workspace = true }
serde_json = { workspace = true }
switchy_fs = { workspace = true, features = [
    "simulator-real-fs",
    "std",
    "sync",
] }
toml = { workspace = true }

[features]
default          = []
fail-on-warnings = ["clippier/fail-on-warnings", "switchy_fs/fail-on-warnings"]
git-diff         = ["clippier/git-diff"]
