[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "MoosicBox assert package"
edition     = { workspace = true }
keywords    = ["assert", "false", "true", "util", "utils"]
license     = { workspace = true }
name        = "moosicbox_assert"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = true

[dependencies]
moosicbox_env_utils = { workspace = true }

colored = { workspace = true }

[dev-dependencies]
log      = { workspace = true }
test-log = { workspace = true }

[features]
default = []

fail-on-warnings = ["moosicbox_env_utils/fail-on-warnings"]
