[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "API endpoint testing simulation using simvar and switchy_web_server"
edition     = { workspace = true }
keywords    = ["api-testing", "rest", "simulation", "simvar"]
license     = { workspace = true }
name        = "simvar_api_testing_example"
publish     = false
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
tests = false

[dependencies]
simvar = { workspace = true, features = [
    "http",
    "random",
    "tcp",
    "time",
    "web-server",
] }
switchy_async = { workspace = true, features = ["simulator", "tokio"] }
switchy_http = { workspace = true, features = ["simulator"] }
switchy_http_models = { workspace = true }
switchy_time = { workspace = true, features = ["simulator"] }
switchy_uuid = { workspace = true, features = ["simulator"] }
switchy_web_server = { workspace = true, features = ["actix", "cors", "serde"] }

log        = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[features]
default = []

fail-on-warnings = [
    "simvar/fail-on-warnings",
    "switchy_async/fail-on-warnings",
    "switchy_http/fail-on-warnings",
    "switchy_http_models/fail-on-warnings",
    "switchy_time/fail-on-warnings",
    "switchy_uuid/fail-on-warnings",
    "switchy_web_server/fail-on-warnings",
]
