[workspace]
members = [
    "packages/pkg-nightly",
    "packages/pkg-no-config",
    "packages/pkg-os-nightly",
    "packages/pkg-stable",
    "packages/pkg-submodules",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
