[package]
authors     = { workspace = true }
categories  = ["network-programming"]
description = "Switchy TCP Networking package"
edition     = { workspace = true }
keywords    = ["network", "networking", "tcp"]
license     = { workspace = true }
name        = "switchy_tcp"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = true

[package.metadata.workspaces]
group = "switchy"

[dependencies]
switchy_async = { workspace = true, default-features = false, features = [
    "io",
    "macros",
    "sync",
    "time",
    "util",
] }

async-trait = { workspace = true }
log         = { workspace = true }
paste       = { workspace = true }
thiserror   = { workspace = true }
tokio       = { workspace = true, features = ["net"] }

# Simulator
bytes      = { workspace = true, optional = true }
flume      = { workspace = true, optional = true }
scoped-tls = { workspace = true, optional = true }

[dev-dependencies]
flume             = { workspace = true, features = ["async"] }
futures           = { workspace = true }
pretty_assertions = { workspace = true }
serial_test       = { workspace = true }
test-log          = { workspace = true }

[features]
default = ["simulator", "tokio"]

fail-on-warnings = ["switchy_async/fail-on-warnings"]

simulator = [
    "dep:bytes",
    "dep:flume",
    "dep:scoped-tls",
    "switchy_async/simulator",
]
tokio = ["switchy_async/tokio"]
