[package]
authors     = ["Braden Steffaniak"]
description = "MoosicBox Tauri App"
edition     = "2021"
license     = ""
name        = "moosicbox_app"
repository  = ""
version     = "0.1.0"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name       = "moosicbox_lib"

[profile.release]
codegen-units = 1
lto           = false
opt-level     = 3
strip         = "symbols"

[profile.release-lto]
inherits = "release"
lto      = "fat"

[profile.release-lto-no-panic]
inherits = "release-lto"
panic    = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta.1", features = [] }

[dependencies]
moosicbox_core   = { path = "../../core", default-features = false }
moosicbox_player = { path = "../../player", default-features = false }

atomic_float     = "0.1.0"
debounce         = "0.2.2"
jni              = "0.21.1"
log              = "0.4.20"
ndk-context      = "0.1.1"
once_cell        = { version = "1.19.0" }
portpicker       = "0.1"
reqwest          = { workspace = true }
serde            = { version = "1.0", features = ["derive"] }
serde_json       = "1.0"
strum            = "0.25.0"
strum_macros     = "0.25.3"
tauri            = { version = "2.0.0-beta.2", features = ["protocol-asset"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }

[features]
# default = ["cpal", "aac", "mp3", "opus"]
default = ["cpal"]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

# Player audio outputs
aac                 = ["moosicbox_player/aac", "moosicbox_core/aac"]
asio                = ["moosicbox_player/asio"]
cpal                = ["moosicbox_player/cpal"]
jack                = ["moosicbox_player/jack"]
mp3                 = ["moosicbox_player/mp3", "moosicbox_core/mp3"]
opus                = ["moosicbox_player/opus", "moosicbox_core/opus"]
pulseaudio          = ["moosicbox_player/pulseaudio"]
pulseaudio-simple   = ["moosicbox_player/pulseaudio-simple"]
pulseaudio-standard = ["moosicbox_player/pulseaudio-standard"]
