[package]
authors     = { workspace = true }
description = "Switchy Web Server Nested GET example"
edition     = { workspace = true }
license     = { workspace = true }
name        = "switchy_web_server_example_nested_get"
publish     = false
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
tests = false

[package.metadata.workspaces]
group = "switchy"

[dependencies]
switchy_async      = { workspace = true, features = ["macros", "tokio"] }
switchy_web_server = { workspace = true, features = ["actix", "cors"] }

env_logger = { workspace = true }

[features]
default = []

fail-on-warnings = [
    "switchy_async/fail-on-warnings",
    "switchy_web_server/fail-on-warnings",
]
