[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "Switchy UUID package"
edition     = { workspace = true }
keywords    = ["identifier", "uuid"]
license     = { workspace = true }
name        = "switchy_uuid"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
examples = true

[package.metadata.workspaces]
group = "switchy"

[dependencies]
log            = { workspace = true }
serde          = { workspace = true, optional = true }
switchy_env    = { workspace = true, optional = true, features = ["simulator"] }
switchy_random = { workspace = true, optional = true, features = ["simulator"] }
uuid           = { workspace = true, features = ["v4"] }

[dev-dependencies]
test-log = { workspace = true }

[features]
default = ["simulator", "uuid"]

fail-on-warnings = [
    "switchy_env?/fail-on-warnings",
    "switchy_random?/fail-on-warnings",
]

serde = ["dep:serde", "uuid/serde"]

simulator = [
    "dep:switchy_env",
    "dep:switchy_random",
    "switchy_env?/simulator",
    "switchy_random?/simulator",
]
uuid = []
