[package]
authors     = { workspace = true }
categories  = ["database"]
description = "Switchy database connection package"
edition     = { workspace = true }
keywords    = ["database", "mysql", "postgres", "sqlite"]
license     = { workspace = true }
name        = "switchy_database_connection"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = true

[package.metadata.workspaces]
group = "switchy"

[dependencies]
switchy_database = { workspace = true }
switchy_env      = { workspace = true, features = ["std"] }

# DB Dependencies
rusqlite = { workspace = true, optional = true }

# sqlx dependencies
sqlx = { workspace = true, optional = true, features = ["runtime-tokio"] }

# tokio-postgres dependencies
deadpool-postgres = { workspace = true, optional = true }
tokio-postgres    = { workspace = true, optional = true, features = [] }

# Postgres dependencies
native-tls          = { workspace = true, optional = true }
openssl             = { workspace = true, optional = true }
postgres-native-tls = { workspace = true, optional = true }
postgres-openssl    = { workspace = true, optional = true }

# Creds dependencies
aws-config  = { workspace = true, optional = true }
aws-sdk-ssm = { workspace = true, optional = true }

log           = { workspace = true }
switchy_async = { workspace = true, optional = true }
thiserror     = { workspace = true }

[dev-dependencies]
serial_test   = { workspace = true }
switchy_async = { workspace = true, features = ["macros", "tokio"] }
test-log      = { workspace = true }
tokio         = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["tokio"]

[features]
default = [
    "mysql-sqlx",
    "postgres-sqlx",
    "simulator",
    "sqlite-rusqlite",
    "sqlite-sqlx",
]

fail-on-warnings = [
    "switchy_async?/fail-on-warnings",
    "switchy_database/fail-on-warnings",
    "switchy_env/fail-on-warnings",
]

simulator = [
    "switchy_async?/simulator",
    "switchy_database/simulator",
    "switchy_env/simulator",
]

tls = ["sqlx/tls-rustls", "switchy_database/tls"]

creds = ["dep:aws-config", "dep:aws-sdk-ssm"]

sqlx = ["dep:sqlx", "switchy_database/sqlx"]

mysql = ["dep:switchy_async", "switchy_database/mysql"]
mysql-sqlx = ["mysql", "sqlx", "sqlx/mysql", "switchy_database/mysql-sqlx"]
postgres = ["dep:switchy_async", "switchy_database/postgres"]
postgres-native-tls = ["dep:native-tls", "dep:postgres-native-tls"]
postgres-openssl = ["dep:openssl", "dep:postgres-openssl"]
postgres-raw = [
    "dep:deadpool-postgres",
    "dep:tokio-postgres",
    "postgres",
    "switchy_database/postgres-raw",
]
postgres-sqlx = [
    "postgres",
    "sqlx",
    "sqlx/postgres",
    "sqlx/tls-rustls",
    "switchy_database/postgres-sqlx",
]
sqlite = ["dep:switchy_async", "switchy_database/sqlite"]
sqlite-rusqlite = ["dep:rusqlite", "sqlite", "switchy_database/sqlite-rusqlite"]
sqlite-sqlx = ["sqlite", "sqlx", "sqlx/sqlite", "switchy_database/sqlite-sqlx"]
turso = ["sqlite", "switchy_database/turso"]

database-connection-turso = ["turso"]
