[package]
authors     = ["Braden Steffaniak"]
categories  = ["development-tools::testing", "simulation"]
description = "MoosicBox Simulator Utils package"
edition     = "2024"
keywords    = ["deterministic", "simulator", "test", "utils"]
license     = "MPL-2.0"
name        = "moosicbox_simulator_utils"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBox"
version     = "0.1.0"

[dependencies]
getrandom = { workspace = true }

[features]
default = []

fail-on-warnings = []
