apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.32.0 (765fde254)
    labels:
        io.kompose.service: moosicbox-server
    name: moosicbox-server
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: moosicbox-server
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert -f compose.yaml
                kompose.version: 1.32.0 (765fde254)
            labels:
                io.kompose.network/moosicboxserver-default: "true"
                io.kompose.service: moosicbox-server
        spec:
            containers:
                - image: registry.digitalocean.com/moosicbox/moosicbox-server
                  imagePullPolicy: Always
                  name: moosicbox-server
                  ports:
                      - containerPort: 8010
                        hostPort: 8010
                        protocol: TCP
            restartPolicy: Always
