[package]
authors     = { workspace = true }
categories  = ["development-tools", "testing"]
description = "Switchy Schema Test Utils package"
edition     = { workspace = true }
keywords    = ["database", "migration", "schema", "testing"]
license     = { workspace = true }
name        = "switchy_schema_test_utils"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
examples = false
tests    = false

[package.metadata.workspaces]
group = "switchy"

[package.metadata.cargo-machete]
ignored = ["switchy_fs", "tokio"]

[dependencies]
async-trait                 = { workspace = true }
log                         = { workspace = true }
switchy_database            = { workspace = true, features = ["schema"] }
switchy_database_connection = { workspace = true, optional = true }
switchy_schema              = { workspace = true, features = ["directory", "embedded"] }
thiserror                   = { workspace = true }

insta      = { workspace = true, features = ["filters", "json"], optional = true }
serde      = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
moosicbox_schema = { workspace = true, features = ["sqlite"] }
switchy_async    = { workspace = true, features = ["macros", "time", "tokio"] }
switchy_fs       = { workspace = true, features = ["simulator-real-fs"] }
test-log         = { workspace = true }
tokio            = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["decimal", "sqlite", "uuid"]

decimal = ["switchy_database/decimal", "switchy_schema/decimal"]
fail-on-warnings = [
    "switchy_database/fail-on-warnings",
    "switchy_database_connection?/fail-on-warnings",
    "switchy_schema/fail-on-warnings",
]
snapshots = [
    "dep:insta",
    "dep:serde",
    "dep:serde_json",
    "sqlite",
    "switchy_schema/snapshots",
]
sqlite = [
    "dep:switchy_database_connection",
    "switchy_database/sqlite",
    "switchy_database_connection?/sqlite",
    "switchy_database_connection?/sqlite-sqlx",
]
uuid = ["switchy_database/uuid", "switchy_schema/uuid"]
