[package]
description = "Example demonstrating port reservation system in openport"
edition     = { workspace = true }
keywords    = ["example", "openport", "port", "reservation"]
license     = { workspace = true }
name        = "openport_port_reservation_example"
publish     = false
repository  = { workspace = true }
version     = "0.1.0"

[[bin]]
name = "port_reservation_example"
path = "src/main.rs"

[dependencies]
openport = { workspace = true, features = ["reservation"] }

[features]
default          = []
fail-on-warnings = ["openport/fail-on-warnings"]
