[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "MoosicBox date utils package"
edition     = { workspace = true }
keywords    = ["date", "time"]
license     = { workspace = true }
name        = "moosicbox_date_utils"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.4"

[package.metadata]
examples = true

[dependencies]
log = { workspace = true }

chrono = { workspace = true, optional = true }

[dev-dependencies]
test-log = { workspace = true }

[features]
default = ["chrono"]

chrono = ["dep:chrono"]

fail-on-warnings = []
