[package]
authors = { workspace = true }
categories = ["development-tools", "network-programming"]
description = "Combined extractors example demonstrating multiple extractors working together"
edition = { workspace = true }
keywords = [
    "async",
    "example",
    "http",
    "json",
    "network",
    "query",
    "serde",
    "web",
]
license = { workspace = true }
name = "combined_extractors_standalone_example"
publish = false
readme = "README.md"
repository = { workspace = true }
version = "0.1.0"

[package.metadata]
tests = false

[features]
actix            = ["moosicbox_web_server/actix"]
default          = ["serde", "simulator"]
fail-on-warnings = ["moosicbox_web_server/fail-on-warnings"]
serde            = ["moosicbox_web_server/serde"]
simulator        = ["moosicbox_web_server/simulator"]

[dependencies]
moosicbox_web_server = { workspace = true, features = ["serde", "simulator"] }
serde                = { workspace = true }
serde_json           = { workspace = true }
