[package]
authors     = { workspace = true }
categories  = ["development-tools", "network-programming"]
description = "MoosicBox Web Server CORS package"
edition     = { workspace = true }
keywords    = ["async", "http", "network", "security", "web"]
license     = { workspace = true }
name        = "moosicbox_web_server_cors"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.1"

[package.metadata]
examples = false

[dependencies]
moosicbox_assert = { workspace = true }

switchy_http_models = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }

[features]
default = []

fail-on-warnings = [
    "moosicbox_assert/fail-on-warnings",
    "switchy_http_models/fail-on-warnings",
]
