[package]
authors     = { workspace = true }
categories  = ["codec", "encoding", "multimedia"]
description = "Pure Rust Opus audio decoder implementation"
edition     = { workspace = true }
keywords    = ["audio", "codec", "decoder", "opus", "rust"]
license     = { workspace = true }
name        = "moosicbox_opus_native"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
examples = false

[dependencies]
log                 = { workspace = true }
moosicbox_resampler = { workspace = true, optional = true }
symphonia           = { workspace = true, optional = true }
thiserror           = { workspace = true }

[dev-dependencies]
moosicbox_opus_native_test_vectors = { workspace = true }
test-case                          = { workspace = true }

[features]
default = ["celt", "hybrid", "silk"]

fail-on-warnings = ["moosicbox_resampler?/fail-on-warnings"]

resampling = ["dep:moosicbox_resampler", "dep:symphonia"]

_any-decoder = []
celt         = ["_any-decoder"]
hybrid       = ["celt", "silk"]
silk         = ["_any-decoder"]
