[package]
authors     = { workspace = true }
categories  = ["development-tools", "testing"]
description = "MoosicBox HyperChad Test Utils package"
edition     = { workspace = true }
keywords    = ["automation", "hyperchad", "testing", "workflow"]
license     = { workspace = true }
name        = "hyperchad_test_utils"
readme      = "README.md"
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
examples = false
tests    = false

[package.metadata.workspaces]
group = "hyperchad"

[dependencies]
moosicbox_assert = { workspace = true }

serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
url        = { workspace = true }

[features]
default = []

fail-on-warnings = ["moosicbox_assert/fail-on-warnings"]
