[package]
authors     = { workspace = true }
description = "MoosicBox Web Server Simple GET example"
edition     = { workspace = true }
license     = { workspace = true }
name        = "web_server_simple_get"
publish     = false
repository  = { workspace = true }
version     = "0.1.0"

[package.metadata]
tests = false

[package.metadata.cargo-machete]
ignored = ["tokio"]

[features]
default = ["simulator"]

fail-on-warnings = [
    "moosicbox_web_server/fail-on-warnings",
    "switchy/fail-on-warnings",
]
simulator = ["moosicbox_web_server/simulator"]

[dependencies]
moosicbox_web_server = { workspace = true, features = [
    "actix",
    "cors",
    "simulator",
] }

env_logger = { workspace = true }
switchy = { workspace = true, features = [
    "async-net",
    "async-rt-multi-thread",
    "async-time",
    "async-tokio",
] }

[dev-dependencies]
switchy_async = { workspace = true, features = ["macros", "tokio"] }
test-log      = { workspace = true }
tokio         = { workspace = true, features = ["macros", "rt"] }
